database:
  file: "local.db"
  sql-user: ""
  sql-pass: ""
  sql-server: "127.0.0.1"
  sql-database: "SupportSystem"
  sql-port: "3306"

  redis:
    server: "localhost:6379"

  sso:
    clientId: "StudentPortal"
    clientSecret: "blabalbal"
    baseAddress: "https://localhost:44375/"
    backBaseAddress: "https://localhost:8080/"